name: CI Pipeline

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login DockerHub
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    
      run: sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    
    - name: Install Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose


    # - name: Build the Docker image
    #   run: sudo docker-compose build -t cicd-pipeline .
    #   image: cicd-pipeline:latest
    # - name: Give a tag to image
    #   run: sudo docker-compose tag cicd-pipeline steeve05/cicd-pipeline
    
    - name: Push to DockerHub
      run: | 
        sudo docker-compose build
        sudo docker-compose push 


